# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

samples: ../config/samples.tsv
STAR_genomes: ../config/STAR_Genome_List.tsv
#STAR_genomes: /project/yangili1/dylan_stermer/mouse_pilot/snakemake-workflow_rna-seq/config/Genome_List_Mouse.tsv

#Prefix for all ReferenceGenomes files... STAR index will be made at {GenomesPrefix}{GenomeName}/

#this is the absolute file path where it will place the Genome Annotation Results 
GenomesPrefix: "/project/yangili1/dylan_stermer/test_git/snakemake-workflow_rna-seq/Results/"
#GenomesPrefix: "/project/yangili1/dylan_stermer/ReferenceGenomes/ncbi_dataset"

#GenomeName: GRCh38_GencodeRelease44Comprehensive
GenomeName: GRCm39 # in the samples.tsv I also changed the STARGenomeName 
#this should allow you to state which species you want to do the analysis in 

#Scratch dir for large temporary files
scratch: "/scratch/midway3/dylanstermer/"