# default snakemake parameters for this profile
restart-times: 1
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
# cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 5
latency-wait: 60
use-conda: True
rerun-incomplete: True
jobs: 150
scheduler: greedy
shadow-prefix: scratch/midway/dylanstermer
#scratch: /project2/yangili1/dylan_stermer/rna-seq_simplequantification/code/config/scratch
 